name: PR Sanity Check

on: pull_request

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-20.04
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Packages
        run: |
          npm ci

      - name: Lint check
        run: |
          npm run lint

      - name: Run tests
        run: |
          npm run test
